s =set()
n =int(input("Enter number of elements: "))
s.add(n)
n =int(input("Enter number of elements: "))
s.add(n)
n =int(input("Enter number of elements: "))
s.add(n)
n =int(input("Enter number of elements: "))
s.add(n)
n =int(input("Enter number of elements: "))
s.add(n)
n =int(input("Enter number of elements: "))
s.add(n)
n =int(input("Enter number of elements: "))
s.add(n)
n =int(input("Enter number of elements: "))
s.add(n)
print("The unique elements are: ",s)